Const
  sTranslatorAuthorCapt	=	200;
  sTranslatorAuthorName	=	201;
  sDefaultFont	=	100;
  sCurrFont	=	101;
  sVersionCapt	=	102;
  sAuthorCapt	=	103;
  s_CopyRight	=	104;
  s_Author	=	105;
  sAbout	=	106;
  stbOpen	=	107;
  smmOpen	=	108;
  stbClose	=	109;
  smmClose	=	110;
  stbSelAll	=	111;
  smmSelAll	=	112;
  stbUnSel	=	113;
  smmUnSel	=	114;
  stbExtract	=	115;
  smmExtract	=	116;
  stbOnTop	=	117;
  smmOnTop	=	118;
  stbLog	=	119;
  smmLog	=	120;
  stbHelp	=	121;
  smmHelp	=	122;
  stbAbout	=	123;
  smmAbout	=	124;
  stbExit	=	125;
  smmExit	=	126;
  sAssMenu	=	127;
  sCopy		=	128;
  sCleanLog	=	129;
  sLogSaveAs	=	130;
  sCleanhistory	=	131;
  sFileName	=	132;
  sFileSize	=	133;
  sFileType	=	134;
  sFileTime	=	135;
  sFilePath	=	136;
  sUnknownType	=	137;
  sError	=	138;
  sIncorrectPwd	=	139;		//the res == innounp lang id 123
  sReading	=	140;
  sReadPP	=	141;
  sExtracting	=	142;
  sReady	=	143;
  sInstScript	=	144;		//the res == innounp lang id 144
  sSelitem	=	145;
  sAppendParam	=	146;
  sLogFilter	=	147;
  sDlgCapt	=	148;
  sExeFilter	=	149;
  sOpenErr	=	150;
  sVerDetected	=	151;		//the res == innounp lang id 134
  sErrCreatPipe	=	152;
  sCommand	=	153;
  sFCProcess	=	154;
  sUsage	=	155;
  sCorrupted	=	156;		//the res == innounp lang id 149,154,155
  sFailed	=	157;		//the res == innounp lang id 130
  sDestPath	=	158;
  sExtraDestDir	=	159;
  sShowPath	=	160;
  sOK		=	161;
  sCancel	=	162;
  sPathWStr	=	163;
  sWrongPwd	=	164;		//the res == innounp lang id 165
  sFindNotFile	=	165;		//the res == innounp lang id 160

  