[LangOptions]
LanguageName=Tatar<00E7>a
LanguageID=$0444
LanguageCodePage=1254
TitleFontName=Arial
WelcomeFontName=Verdana
CopyrightFontName=Arial
DialogFontSize=8
TitleFontSize=29
WelcomeFontSize=12
CopyrightFontSize=8
